feat: add all gitignore types, update go version

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,145 +1,80 @@
-name: build
+name: Release
 
 on:
-  create:
-    tags:
-      - v*
+  push:
+    branches:
+      - master
 
-permissions: write-all
+permissions:
+  contents: write
+  pull-requests: write
 
 jobs:
-  Build:
+  test:
+    name: Test
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-      # - name: Generate build files
-      #   uses: thatisuday/go-cross-build@v1
-      #   with:
-      #     platforms: "windows/386, linux/arm64, linux/amd64, darwin/arm64, darwin/amd64"
-      #     package: ""
-      #     name: "gi_gen"
-      #     dest: "dist"
-      - name: Generate Build Files
-        uses: crazy-max/ghaction-xgo@v1
+      - uses: actions/checkout@v4
+      - name: Set up Go
+        uses: actions/setup-go@v4
         with:
-          xgo_version: latest
-          go_version: 1.18
-          dest: dist
-          prefix: gi_gen
-          targets: windows/386, linux/amd64, linux/arm64, linux/386, darwin/arm64, darwin/amd64
-          v: true
-          x: false
-          race: false
-          ldflags: -s -w
-          buildmode: default
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: dist
-          path: dist
-          retention-days: 1
+          go-version: "1.23"
+      - name: Test
+        run: go test -v
 
-  Release:
+  generate:
+    name: Generate cross-platform builds
     runs-on: ubuntu-latest
-    needs: Build
     steps:
-      - name: Download Artifact
-        uses: actions/download-artifact@v3
+      - name: Checkout the repository
+        uses: actions/checkout@v4
+      - name: Create dist/ dir
+        run: mkdir dist
+      - name: Generate build files
+        uses: chenasraf/go-cross-build@v1
+        with:
+          platforms: "linux/amd64, darwin/amd64, windows/amd64" # , darwin/arm64' # '
+          package: ""
+          name: "gi_gen"
+          compress: "true"
+          dest: "dist"
+      - name: Upload builds
+        uses: actions/upload-artifact@v4
         with:
           name: dist
           path: dist
 
-      - name: List Files
+  release-please:
+    name: Release
+    runs-on: ubuntu-latest
+    needs:
+      - test
+      - generate
+    steps:
+      - name: Download builds
+        uses: actions/download-artifact@v4
+        with:
+          name: dist
+          path: dist
+      - name: Verify Release Artifacts
         run: |
-          ls -l ./
-          ls -l ./dist
-          file -b --mime-type ./dist/gi_gen-darwin-10.16-arm64
-
-      - name: Create Release
-        # if: steps.update_tag.outputs.tagname && !contains(github.event.head_commit.message, '[skip publish]')
-        uses: actions/create-release@v1
-        id: create_release
+          ls -la dist
+          for i in "linux-amd64" "darwin-amd64" "windows-amd64"; do
+            if [[ ! -f ./dist/gi_gen-$i.tar.gz ]]; then
+              echo "File not found: ./dest/gi_gen-$i.tar.gz"
+              exit 1
+            fi
+          done
+      - uses: googleapis/release-please-action@v4
+        id: release
+        with:
+          release-type: simple
+      - name: Upload Release Artifacts
+        if: ${{ steps.release.outputs.release_created }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: ${{ github.event.ref }}
-          release_name: Release ${{ github.event.ref }}
-
-      #
-
-      - name: Upload Release Asset (macOS ARM)
-        # if: steps.update_tag.outputs.tagname && !contains(github.event.head_commit.message, '[skip publish]')
-        id: upload_release_asset_macos_arm
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./dist/gi_gen-darwin-10.16-arm64
-          asset_name: gi_gen-${{ github.event.ref }}-macos-arm
-          asset_content_type: application/octet-stream
-
-      - name: Upload Release Asset (macOS Intel)
-        # if: steps.update_tag.outputs.tagname && !contains(github.event.head_commit.message, '[skip publish]')
-        id: upload_release_asset_macos_x86
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./dist/gi_gen-darwin-10.16-amd64
-          asset_name: gi_gen-${{ github.event.ref }}-macos-intel
-          asset_content_type: application/octet-stream
-
-      #
-
-      - name: Upload Release Asset (Windows)
-        # if: steps.update_tag.outputs.tagname && !contains(github.event.head_commit.message, '[skip publish]')
-        id: upload_release_asset_windows
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./dist/gi_gen-windows-4.0-386.exe
-          asset_name: gi_gen-${{ github.event.ref }}-windows.exe
-          asset_content_type: application/vnd.microsoft.portable-executable
-
-      #
-
-      - name: Upload Release Asset (Linux 386)
-        # if: steps.update_tag.outputs.tagname && !contains(github.event.head_commit.message, '[skip publish]')
-        id: upload_release_asset_linux_386
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./dist/gi_gen-linux-386
-          asset_name: gi_gen-${{ github.event.ref }}-linux-386
-          asset_content_type: application/octet-stream
-
-      - name: Upload Release Asset (Linux amd64)
-        # if: steps.update_tag.outputs.tagname && !contains(github.event.head_commit.message, '[skip publish]')
-        id: upload_release_asset_linux_amd64
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./dist/gi_gen-linux-amd64
-          asset_name: gi_gen-${{ github.event.ref }}-linux-amd64
-          asset_content_type: application/octet-stream
-
-      - name: Upload Release Asset (Linux ARM)
-        # if: steps.update_tag.outputs.tagname && !contains(github.event.head_commit.message, '[skip publish]')
-        id: upload_release_asset_linux_arm
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./dist/gi_gen-linux-arm64
-          asset_name: gi_gen-${{ github.event.ref }}-linux-arm
-          asset_content_type: application/octet-stream
+        run: |
+          gh release upload ${{ steps.release.outputs.tag_name }} ./dist/gi_gen-linux-amd64.tar.gz
+          gh release upload ${{ steps.release.outputs.tag_name }} ./dist/gi_gen-darwin-amd64.tar.gz
+          gh release upload ${{ steps.release.outputs.tag_name }} ./dist/gi_gen-windows-amd64.zip
+          # gh release upload ${{ steps.release.outputs.tag_name }} ./dist/gi_gen-darwin-arm64.tar.gz
